abstract class AddNewMedicalEquipmentsStates {}

class AddNewMedicalEquipmentsInitialState extends AddNewMedicalEquipmentsStates {}

class AddNewMedicalEquipmentsLoadingState extends AddNewMedicalEquipmentsStates {}

class AddNewMedicalEquipmentsSuccessState extends AddNewMedicalEquipmentsStates {}

class AddNewMedicalEquipmentsErrorState extends AddNewMedicalEquipmentsStates {}
